Add the possibility to select an update frequency when creating batches
arkhn/pyrog pull request #525
Opened 2021-06-08 16:18 UTC by Jasopaum

2021-06-09 09:33 UTC, simonvadee requested changes

2021-06-09 09:33 UTC, simonvadee commented on client/src/components/river/index.tsx
> +    const runOnce = selectedFrequency === "run once"
naming confused me at first, I suggest 
```suggestion
    const isRecurring = selectedFrequency !== "run once"
```

2021-06-09 09:33 UTC, simonvadee commented on client/src/components/river/index.tsx
> +    const runOnce = selectedFrequency === "run once"
I think it will make the rest of this function clearer

2021-06-09 09:33 UTC, simonvadee commented on client/src/components/river/index.tsx
> +    const route =  runOnce? "api/batch/" : "api/update-batch/";
very nit: I would have put this ternary directly in the template string when calling axios

2021-06-09 09:33 UTC, simonvadee commented on client/src/components/selects/stringSelect.tsx
> +    const doSort = (this.props.doSort === undefined || this.props.doSort === true);
can't you have default props value instead ?

2021-06-24 13:25 UTC, simonvadee reviewed
do we want to merge this one or leave it as a separate branch since we're not going to merge [this one](https://github.com/arkhn/fhir-river/pull/443) ?

2022-02-02 15:56 UTC, Jasopaum commented
We don't use pyrog anymore

2022-02-02 15:56 UTC, closed without merging